name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 배포 시작
        run: echo "Starting deployment..."

      - name: SSH 키 준비
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: AWS EC2에 배포
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd ~/gateway
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker ps
          EOF

      - name: 배포 완료
        run: echo "Deployment completed!"
